#!/bin/bash

ln -sf .dotfiles/.gtkrc-2.0.mine .
ln -sf .dotfiles/.bash .
ln -sf .dotfiles/.tmux.conf .
ln -sf .dotfiles/.scripts .
ln -sf .dotfiles/.zshrc .

if [ "$1" == "vdr" ]; then
    ln -sf .dotfiles/.vimrc .vimrc
    ln -sf .dotfiles/.vim .vim
    ln -sf .dotfiles/.tmux .tmux
elif [ "$1" == "debian" ]; then
    ln -sf .dotfiles/.inputrc_debian .inputrc
    ln -sf .dotfiles/.vimrc .vimrc
    ln -sf .dotfiles/.vim .vim
    ln -sf .dotfiles/.tmux .tmux
else
    echo "unknown?!"
fi
