#!/usr/bin/env sh
ssid=`iwgetid --scheme`
active_connection=`nmcli -t connection show --active | cut -d: -f 1 | head -n1`
echo $active_connection
zone=`nmcli -t connection show $active_connection | grep connection.zone | awk -F':' '{ print $2 }' | head -n1`
echo ssid $ssid
echo zone "$zone"
if [[ $zone == "home" ]]; then
    echo "at home!"
    exit
else
    echo "not at home!"
    exit 1
fi
