#!/usr/bin/env sh
ssid=`iwgetid --scheme`
active_connection=`nmcli -t connection show --active | grep wireless | cut -d: -f 1 | head -n1`
zone=`nmcli -t -f connection.zone connection show $active_connection | awk -F':' '{ print $2 }'`
echo ssid $ssid
echo zone $zone
if [[ $zone = "home" ]]; then
    echo "at home!"
    exit
else
    echo "not at home!"
    exit 1
fi
