#!/usr/bin/env sh
ssid=`iwgetid --scheme`
zone=`nmcli -t -f connection.zone connection show wired@home | awk -F':' '{ print $2 }'`
echo ssid $ssid
echo zone $zone
if [[ $zone = "home" ]]; then
    echo "at home!"
    exit
else
    echo "not at home!"
    exit 1
fi
