#!/usr/bin/env zsh
command=${@:-zsh}
echo "Running $command in nix-shell..."

if [ -e "shell.drv" ]; then
    echo "using persistent shell"
    nix-shell $(pwd)/shell.drv --run "$command"
else
    nix-shell --run "$command"
fi
